import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Main from "./home";

export default function Home() {
	return (
		<>
			<Head>
				<title>I Want TV</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<Main />
		</>
	);
}
